openapi: 3.0.0
info:
  title: Petstore API
  description: API for managing a pet store
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
paths:
  /pets:
    get:
      summary: Get all pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Add a new pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Pet added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

  /pets/{petId}:
    get:
      summary: Get a specific pet by ID
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A pet object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
    put:
      summary: Update a specific pet by ID
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
    delete:
      summary: Delete a specific pet by ID
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Pet deleted
        '404':
          description: Pet not found

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the pet
        name:
          type: string
          description: The name of the pet
        status:
          type: string
          description: The status of the pet (e.g., available, pending, sold)
